### PR TITLE
Bootstrap 4 fixes

### PR DESCRIPTION
**Pull request by bitterdev**

### CODE REVIEW

**Comment by mlocati** [comment]
I wouldn't add the `.idea` directory to this repository

**Review by KorvinSzanto — CHANGES_REQUESTED** [review]
Please remove development files

**Comment by mlocati** [comment]
@bitterdev is this PR still applicable?

**Comment by aembler** [comment]
I think it probably is – it's true we use Bootstrap 5 in the core but our new Concrete CMS theme used on translate.concretecms.org is still Bootstrap 4

**Pull request closed without merging**
