### PR TITLE
Add API Rate Limit support

### PR DESCRIPTION
**Pull request by mlocati**
@KorvinSzanto What should I do to add a 3rd party composer library?

In this pull request
- I updated the `composer.json` file by adding the required library
- I updated the package version
- I included the new composer autoload to the package `on_start`

Questions:
1. Should I add the `composer.lock` file too?
2. Is this correct to add the new autoload with  
  `require $this->getPackagePath() . '/vendor/autoload.php';`  
  ?

### CODE REVIEW

**Comment by mlocati** [comment]
Just a question for @aembler:

This PR adds [IPLib](https://github.com/mlocati/ip-lib) as a composer dependency to CommunityTranslation.

BTW I'm planning to revamp the current blacklist control of concrete5 (see https://github.com/concrete5/concrete5/issues/3149 and https://github.com/concrete5/concrete5/issues/5029), by using the same IPLib.

So, what about adding IPLib to the core right now, instead of adding it to CommunityStore ?

**Comment by aembler** [comment]
Looks like a great library to me (kudos mlocati) – I wouldn't have a
problem adding it into the core.

**Comment by mlocati** [comment]
Great!

**Comment by KorvinSzanto** [comment]
@mlocati I'd use `__DIR__ . "/vendor/autoload.php";` The rest you're on the right track with. You don't really need the .lock for this project but you can have it if you see a need for it. Ideally the composer.json won't allow any versions that aren't compatible.

**Pull request closed without merging**
