### PR TITLE
improve column widths

### PR DESCRIPTION
**Pull request by Remo**
OLD:
image

NEW:
image

### CODE REVIEW

**Comment by mlocati** [comment]
I think that the place where people actually translate is more important than the translation list. Think for instance if you have to translate a long string: the textbox would be very narrow...

**Comment by Remo** [comment]
See my message on telegram, that's why I'd like to have a textarea instead of an input field so that we can see the full translations there too.

**Comment by mlocati** [comment]
That makes sense... Sorry for not having seen your message before... gmail, thunderbird and slack were distracting me :wink:

**Comment by Remo** [comment]
Sorry, will send you a snail mail and a carrier pigeon to ensure fast delivery next time!

**Comment by mlocati** [comment]
Deployed to https://translate.concrete5.org

**Pull request merged**
